name: CI - Java Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java (JDK 17 for your pom.xml)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the project with Maven
      - name: Build with Maven
        run: mvn clean package

      # Run tests
      - name: Run tests
        run: mvn test

      # Save the JAR file as a workflow artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-jar
          path: target/*.jar
